version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - mysql
  mongo:
    image: mongo:latest
    database: journaldev
    ports:
      - 27017:27017
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=prod
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
